"""initial

Revision ID: e3dbec4f5e22
Revises: 
Create Date: 2024-10-22 23:34:27.117131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3dbec4f5e22"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_table(
        "auth_methods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("method", sa.Enum("TELEGRAM", name="authmethodenum"), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("auth_methods_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_methods_pkey")),
    )
    op.create_table(
        "auth_methods_with_password",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "method",
            sa.Enum("EMAIL", "TELEPHONE", name="authmethodwithpasswordenum"),
            nullable=False,
        ),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("auth_methods_with_password_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_methods_with_password_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_methods_with_password")
    op.drop_table("auth_methods")
    op.drop_table("users")
    # ### end Alembic commands ###
