"""temp_user

Revision ID: 6f43591c565a
Revises: 9253a4cdd498
Create Date: 2024-10-23 18:22:56.224902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f43591c565a"
down_revision: Union[str, None] = "9253a4cdd498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temp_users", sa.Column("otp_type", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "temp_users", sa.Column("otp_code", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("temp_users", "otp_code")
    op.drop_column("temp_users", "otp_type")
    # ### end Alembic commands ###
